import type { Metadata } from "next";
import { Inter,Bona_Nova } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";


const inter = Bona_Nova({ subsets: ["latin"], weight:'400' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Toaster/>
        {children}
        </body>
    </html>
  );
}
