import type { Metadata } from "next";
import { Inter, Bona_Nova } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import DragProvider from "@/lib/DragProvider";
import PersistProvider from "@/lib/PersistProvider";
import Script from "next/script";

const inter = Bona_Nova({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Image formatter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <PersistProvider>
          {/* <DragProvider> */}
          {children}
          {/* </DragProvider> */}
        </PersistProvider>
      </body>
      <Script src="/path/to/cropper.js" />
    </html>
  );
}
